"""initial schema for M0-M4

Revision ID: 5b67d2c537eb
Revises: 
Create Date: 2026-09-22 10:58:29.026173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b67d2c537eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('director', 'teacher', name='user_role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('login_id', name=op.f('uq_app_user_login_id'))
    )
    op.create_table('campus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campus'))
    )
    op.create_table('app_user_campus',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_app_user_campus_campus_id')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_app_user_campus_user_id')),
    sa.PrimaryKeyConstraint('user_id', 'campus_id', name=op.f('pk_app_user_campus'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], name=op.f('fk_audit_log_actor_id')),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_audit_log_campus_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_campus_id'), 'audit_log', ['campus_id'], unique=False)
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_class_campus_id')),
    sa.ForeignKeyConstraint(['teacher_id'], ['app_user.id'], name=op.f('fk_class_teacher_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class'))
    )
    op.create_index(op.f('ix_class_campus_id'), 'class', ['campus_id'], unique=False)
    op.create_table('grade_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Enum('A+', 'A', 'B', 'C', 'D', 'F', name='homework_grade', native_enum=False), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_grade_comment_campus_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_comment')),
    sa.UniqueConstraint('campus_id', 'grade', name=op.f('uq_grade_comment_campus_id_grade'))
    )
    op.create_index(op.f('ix_grade_comment_campus_id'), 'grade_comment', ['campus_id'], unique=False)
    op.create_table('integration_setting',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_integration_setting_campus_id')),
    sa.PrimaryKeyConstraint('campus_id', 'key', name=op.f('pk_integration_setting'))
    )
    op.create_table('message_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_message_template_campus_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_template'))
    )
    op.create_index(op.f('ix_message_template_campus_id'), 'message_template', ['campus_id'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('enrolled', 'paused', 'withdrawn', name='student_status', native_enum=False), nullable=False),
    sa.Column('omr_number', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_student_campus_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student')),
    sa.UniqueConstraint('campus_id', 'omr_number', name=op.f('uq_student_campus_id_omr_number'))
    )
    op.create_index(op.f('ix_student_campus_id'), 'student', ['campus_id'], unique=False)
    op.create_table('class_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name=op.f('fk_class_schedule_class_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_schedule'))
    )
    op.create_index(op.f('ix_class_schedule_class_id'), 'class_schedule', ['class_id'], unique=False)
    op.create_table('class_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('homework', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('teacher_note', sa.Text(), nullable=True),
    sa.Column('test_name', sa.String(length=100), nullable=True),
    sa.Column('test_max_score', sa.Integer(), nullable=True),
    sa.Column('attendance_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attendance_confirmed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_confirmed_by'], ['app_user.id'], name=op.f('fk_class_session_attendance_confirmed_by')),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name=op.f('fk_class_session_class_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_session')),
    sa.UniqueConstraint('class_id', 'session_date', name=op.f('uq_class_session_class_id_session_date'))
    )
    op.create_index(op.f('ix_class_session_class_id'), 'class_session', ['class_id'], unique=False)
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name=op.f('fk_enrollment_class_id')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_enrollment_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment'))
    )
    op.create_index(op.f('ix_enrollment_class_id'), 'enrollment', ['class_id'], unique=False)
    op.create_index(op.f('ix_enrollment_student_id'), 'enrollment', ['student_id'], unique=False)
    op.create_table('guardian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_notify_target', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_guardian_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardian'))
    )
    op.create_index(op.f('ix_guardian_student_id'), 'guardian', ['student_id'], unique=False)
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('recipient_type', sa.Enum('student', 'guardian', name='recipient_type', native_enum=False), nullable=False),
    sa.Column('recipient_phone', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'lms', 'mms', 'alimtalk', name='message_channel', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('test', 'queued', 'sent', 'failed', 'fallback_sent', name='message_status', native_enum=False), nullable=False),
    sa.Column('body_snapshot', sa.Text(), nullable=False),
    sa.Column('cost_unit', sa.Integer(), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result_code', sa.String(length=50), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_message_log_campus_id')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_message_log_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_log'))
    )
    op.create_index(op.f('ix_message_log_campus_id'), 'message_log', ['campus_id'], unique=False)
    op.create_index(op.f('ix_message_log_student_id'), 'message_log', ['student_id'], unique=False)
    op.create_table('class_session_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['class_session.id'], name=op.f('fk_class_session_progress_session_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_session_progress')),
    sa.UniqueConstraint('session_id', 'period', name=op.f('uq_class_session_progress_session_id_period'))
    )
    op.create_index(op.f('ix_class_session_progress_session_id'), 'class_session_progress', ['session_id'], unique=False)
    op.create_table('student_daily_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attendance_status', sa.Enum('unchecked', 'present', 'late', 'absent', 'early_leave', name='attendance_status', native_enum=False), nullable=False),
    sa.Column('attendance_reason', sa.String(length=200), nullable=True),
    sa.Column('homework_grade', sa.Enum('A+', 'A', 'B', 'C', 'D', 'F', name='homework_grade', native_enum=False), nullable=True),
    sa.Column('recheck_result', sa.Enum('pass', 'fail', name='recheck_result', native_enum=False), nullable=True),
    sa.Column('test_score_num', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('test_score_text', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['class_session.id'], name=op.f('fk_student_daily_record_session_id')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_daily_record_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_daily_record')),
    sa.UniqueConstraint('session_id', 'student_id', name=op.f('uq_student_daily_record_session_id_student_id'))
    )
    op.create_index(op.f('ix_student_daily_record_session_id'), 'student_daily_record', ['session_id'], unique=False)
    op.create_index(op.f('ix_student_daily_record_student_id'), 'student_daily_record', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_daily_record_student_id'), table_name='student_daily_record')
    op.drop_index(op.f('ix_student_daily_record_session_id'), table_name='student_daily_record')
    op.drop_table('student_daily_record')
    op.drop_index(op.f('ix_class_session_progress_session_id'), table_name='class_session_progress')
    op.drop_table('class_session_progress')
    op.drop_index(op.f('ix_message_log_student_id'), table_name='message_log')
    op.drop_index(op.f('ix_message_log_campus_id'), table_name='message_log')
    op.drop_table('message_log')
    op.drop_index(op.f('ix_guardian_student_id'), table_name='guardian')
    op.drop_table('guardian')
    op.drop_index(op.f('ix_enrollment_student_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_class_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_class_session_class_id'), table_name='class_session')
    op.drop_table('class_session')
    op.drop_index(op.f('ix_class_schedule_class_id'), table_name='class_schedule')
    op.drop_table('class_schedule')
    op.drop_index(op.f('ix_student_campus_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_message_template_campus_id'), table_name='message_template')
    op.drop_table('message_template')
    op.drop_table('integration_setting')
    op.drop_index(op.f('ix_grade_comment_campus_id'), table_name='grade_comment')
    op.drop_table('grade_comment')
    op.drop_index(op.f('ix_class_campus_id'), table_name='class')
    op.drop_table('class')
    op.drop_index(op.f('ix_audit_log_campus_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_user_campus')
    op.drop_table('campus')
    op.drop_table('app_user')
    # ### end Alembic commands ###
