"""schema 2 exam omr consult file llm

Revision ID: 6f28fe0c3cac
Revises: 9c040c3bb194
Create Date: 2026-09-22 23:50:37.034645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f28fe0c3cac'
down_revision: Union[str, Sequence[str], None] = '9c040c3bb194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_correction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('source_ref', sa.String(length=200), nullable=False),
    sa.Column('before_value', sa.Text(), nullable=True),
    sa.Column('after_value', sa.Text(), nullable=True),
    sa.Column('asset_ref', sa.String(length=500), nullable=True),
    sa.Column('corrected_by', sa.Integer(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by'], ['app_user.id'], name=op.f('fk_label_correction_corrected_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label_correction'))
    )
    op.create_index(op.f('ix_label_correction_kind'), 'label_correction', ['kind'], unique=False)
    op.create_table('stored_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_stored_file_campus_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stored_file'))
    )
    op.create_index(op.f('ix_stored_file_campus_id'), 'stored_file', ['campus_id'], unique=False)
    op.create_index(op.f('ix_stored_file_kind'), 'stored_file', ['kind'], unique=False)
    op.create_index(op.f('ix_stored_file_sha256'), 'stored_file', ['sha256'], unique=False)
    op.create_table('consult_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('consulted_on', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], name=op.f('fk_consult_log_author_id')),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_consult_log_campus_id')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_consult_log_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consult_log'))
    )
    op.create_index(op.f('ix_consult_log_campus_id'), 'consult_log', ['campus_id'], unique=False)
    op.create_index(op.f('ix_consult_log_consulted_on'), 'consult_log', ['consulted_on'], unique=False)
    op.create_index(op.f('ix_consult_log_student_id'), 'consult_log', ['student_id'], unique=False)
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'confirmed', name='exam_status', native_enum=False), nullable=False),
    sa.Column('answer_key_odd', sa.JSON(), nullable=True),
    sa.Column('answer_key_even', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_exam_campus_id')),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name=op.f('fk_exam_class_id')),
    sa.ForeignKeyConstraint(['source_file_id'], ['stored_file.id'], name=op.f('fk_exam_source_file_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam'))
    )
    op.create_index(op.f('ix_exam_campus_id'), 'exam', ['campus_id'], unique=False)
    op.create_index(op.f('ix_exam_class_id'), 'exam', ['class_id'], unique=False)
    op.create_table('exam_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.Enum('odd', 'even', name='form_type', native_enum=False), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source', sa.Enum('omr', 'manual', name='attempt_source', native_enum=False), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('fk_exam_attempt_exam_id')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_exam_attempt_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_attempt')),
    sa.UniqueConstraint('exam_id', 'student_id', name=op.f('uq_exam_attempt_exam_id_student_id'))
    )
    op.create_index(op.f('ix_exam_attempt_exam_id'), 'exam_attempt', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_attempt_student_id'), 'exam_attempt', ['student_id'], unique=False)
    op.create_table('exam_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=200), nullable=True),
    sa.Column('sub_type', sa.String(length=200), nullable=True),
    sa.Column('difficulty', sa.Enum('low', 'mid', 'high', 'top', name='difficulty', native_enum=False), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('fk_exam_question_exam_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_question')),
    sa.UniqueConstraint('exam_id', 'no', name=op.f('uq_exam_question_exam_id_no'))
    )
    op.create_index(op.f('ix_exam_question_exam_id'), 'exam_question', ['exam_id'], unique=False)
    op.create_table('llm_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.Enum('test', 'anthropic', 'openai_compat', name='llm_provider', native_enum=False), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_llm_call_log_campus_id')),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('fk_llm_call_log_exam_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_call_log'))
    )
    op.create_index(op.f('ix_llm_call_log_campus_id'), 'llm_call_log', ['campus_id'], unique=False)
    op.create_index(op.f('ix_llm_call_log_exam_id'), 'llm_call_log', ['exam_id'], unique=False)
    op.create_index(op.f('ix_llm_call_log_purpose'), 'llm_call_log', ['purpose'], unique=False)
    op.create_table('omr_scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('read', 'needs_review', 'applied', name='omr_scan_status', native_enum=False), nullable=False),
    sa.Column('matched_student_id', sa.Integer(), nullable=True),
    sa.Column('read_payload', sa.JSON(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('fk_omr_scan_exam_id')),
    sa.ForeignKeyConstraint(['file_id'], ['stored_file.id'], name=op.f('fk_omr_scan_file_id')),
    sa.ForeignKeyConstraint(['matched_student_id'], ['student.id'], name=op.f('fk_omr_scan_matched_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omr_scan'))
    )
    op.create_index(op.f('ix_omr_scan_exam_id'), 'omr_scan', ['exam_id'], unique=False)
    op.create_table('exam_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_no', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.String(length=20), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempt.id'], name=op.f('fk_exam_answer_attempt_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_answer')),
    sa.UniqueConstraint('attempt_id', 'question_no', name=op.f('uq_exam_answer_attempt_id_question_no'))
    )
    op.create_index(op.f('ix_exam_answer_attempt_id'), 'exam_answer', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_answer_attempt_id'), table_name='exam_answer')
    op.drop_table('exam_answer')
    op.drop_index(op.f('ix_omr_scan_exam_id'), table_name='omr_scan')
    op.drop_table('omr_scan')
    op.drop_index(op.f('ix_llm_call_log_purpose'), table_name='llm_call_log')
    op.drop_index(op.f('ix_llm_call_log_exam_id'), table_name='llm_call_log')
    op.drop_index(op.f('ix_llm_call_log_campus_id'), table_name='llm_call_log')
    op.drop_table('llm_call_log')
    op.drop_index(op.f('ix_exam_question_exam_id'), table_name='exam_question')
    op.drop_table('exam_question')
    op.drop_index(op.f('ix_exam_attempt_student_id'), table_name='exam_attempt')
    op.drop_index(op.f('ix_exam_attempt_exam_id'), table_name='exam_attempt')
    op.drop_table('exam_attempt')
    op.drop_index(op.f('ix_exam_class_id'), table_name='exam')
    op.drop_index(op.f('ix_exam_campus_id'), table_name='exam')
    op.drop_table('exam')
    op.drop_index(op.f('ix_consult_log_student_id'), table_name='consult_log')
    op.drop_index(op.f('ix_consult_log_consulted_on'), table_name='consult_log')
    op.drop_index(op.f('ix_consult_log_campus_id'), table_name='consult_log')
    op.drop_table('consult_log')
    op.drop_index(op.f('ix_stored_file_sha256'), table_name='stored_file')
    op.drop_index(op.f('ix_stored_file_kind'), table_name='stored_file')
    op.drop_index(op.f('ix_stored_file_campus_id'), table_name='stored_file')
    op.drop_table('stored_file')
    op.drop_index(op.f('ix_label_correction_kind'), table_name='label_correction')
    op.drop_table('label_correction')
    # ### end Alembic commands ###
