"""background task

Revision ID: 980c6aafb97c
Revises: 6f28fe0c3cac
Create Date: 2026-09-24 01:53:40.108696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980c6aafb97c'
down_revision: Union[str, Sequence[str], None] = '6f28fe0c3cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='task_status', native_enum=False), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_background_task_campus_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_task'))
    )
    op.create_index(op.f('ix_background_task_campus_id'), 'background_task', ['campus_id'], unique=False)
    op.create_index(op.f('ix_background_task_kind'), 'background_task', ['kind'], unique=False)
    op.create_index(op.f('ix_background_task_status'), 'background_task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_background_task_status'), table_name='background_task')
    op.drop_index(op.f('ix_background_task_kind'), table_name='background_task')
    op.drop_index(op.f('ix_background_task_campus_id'), table_name='background_task')
    op.drop_table('background_task')
    # ### end Alembic commands ###
