"""login lockout columns

Revision ID: 9c040c3bb194
Revises: 977a7bf03a58
Create Date: 2026-09-22 17:41:59.626085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c040c3bb194'
down_revision: Union[str, Sequence[str], None] = '977a7bf03a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('app_user', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'locked_until')
    op.drop_column('app_user', 'failed_login_count')
    # ### end Alembic commands ###
